spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_exercise
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

